parameters:


    tvision_rackspace_cloud_files.service.class: Tvision\RackspaceCloudFilesStreamWrapper\Service\RSCFService
    tvision_rackspace_cloud_files.api.service.class: Tvision\RackspaceCloudFilesStreamWrapper\Service\RackspaceApi
    tvision_rackspace_cloud_files.api.connection.class: OpenCloud\Rackspace

    tvision_rackspace_cloud_files.resource_entity.class: Tvision\RackspaceCloudFilesStreamWrapper\Model\RackspaceCloudFilesResource
    tvision_rackspace_cloud_files.filetype_guesser_entity.class: Tvision\RackspaceCloudFilesStreamWrapper\Service\FileTypeGuesser

services:

    tvision_rackspace_cloud_files.api.service:
        class: %tvision_rackspace_cloud_files.api.service.class%
        arguments: [%tvision_rackspace_cloud_files.api.connection.class%, %tvision_rackspace_cloud_files.auth.host%, %tvision_rackspace_cloud_files.auth.username%, %tvision_rackspace_cloud_files.auth.api_key%, %tvision_rackspace_cloud_files.auth.container_name%]

    tvision_rackspace_cloud_files.service:
        class: %tvision_rackspace_cloud_files.service.class%
        arguments: [%tvision_rackspace_cloud_files.stream_wrapper.protocol_name%, '@tvision_rackspace_cloud_files.api.service', %tvision_rackspace_cloud_files.stream_wrapper.class%, %tvision_rackspace_cloud_files.resource_entity.class%, %tvision_rackspace_cloud_files.filetype_guesser_entity.class%]
